apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaseapp-staging
resources:
  - ../base
  - namespace.yaml
patchesStrategicMerge:
  - ingress.yaml
images:
  - name: ghcr.io/carverauto/chaseapp-web
    newTag: staging
