apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaseapp
commonLabels:
  app.kubernetes.io/name: chaseapp
  app.kubernetes.io/part-of: chaseapp
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml

images:
  - name: ghcr.io/carverauto/chaseapp-web
    newTag: latest
